---
title: "Home"
output:
  html_document:
    toc: true
---

This is a website for organizing my work and persionally recording my daily progress. 

If you have any question about this project, please feel free to contact me:
[Ziwei LIU](https://github.com/ziweil8/live-demo), `ziweil8@student.unimelb.edu.au`.

***

## Reading

### Biology

#### [Oleg 2011]()

- Statistical Aspects of ChIP-Seq Data Analysis
- Paper: https://escholarship.org/uc/item/1ss936z1
- Note: [link]()

#### [Ingrid's script]()

- Compare histone mark ChIP-seq abundance between libraries
- Note: [link]()

### Statistics

#### [Terry Speed,2013]()

- Removing Unwanted Variation from High Dimensional Data with Negative Controls
- Paper: https://statistics.berkeley.edu/tech-reports/820
- Note: [link]()
- R!tutorial of RUV[Part1_link](https://www.youtube.com/watch?v=Z9IjfmSRfVU)[Part2_link](https://www.youtube.com/watch?v=HUcZQC3xWDo&t=0s&index=5&list=PL4IzsxWztPdnyAKQQLxA4ucpaCLdsKvZw)

#### [Background of RUV]()

- Removing Unwanted Variation-Exploiting Negative Controls for High Dimensional Data
- Note: [link]()

***

## Simulation

#### [Russ,2017]()
- Regulation of H3K4me3 at Transcriptional Enhancers Characterizes Acquisition of Virus-Specific CD8+ T Cell-Lineage-Specific Function
- Paper: [link](https://www.cell.com/cell-reports/fulltext/S2211-1247(17)31779-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2211124717317795%3Fshowall%3Dtrue#secsectitle0130)
- Note: [link]()
- process:[link](first-analysis)

